config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :labs
  resources :checklist_components
  resources :experiments

  devise_scope :user do
    authenticated :user do
     root 'lab#index', as: :authenticated_root
    end
    unauthenticated do
     root 'devise/sessions#new', as: :unauthenticated_root
   end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checklist_component.rb
class ChecklistComponent < ApplicationRecord
  belongs_to :experiment
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  has_many :checklistComponents
  belongs_to :lab
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_many :users
end

app/models/manager.rb
class Manager < User
end

app/models/normal.rb
class Normal < User
end

app/models/super_admin.rb
class SuperAdmin < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :lab

  validates :email, uniqueness: true
    
  def is_normal?
    type == 'Normal'
  end

  def is_manager?
    type == 'Manager'
  end

  def is_super_admin?
    type == 'SuperAdmin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # rescue_from Pundit::NotAuthorizedError, redirect_to(lab_show_path)
end

app/controllers/checklist_components_controller.rb
class ChecklistComponentsController < ApplicationController
  def index
    @checklistComponents = ChecklistComponent.where(experiment_id: params[:experiment_id])
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def index
    @experiments = Experiment.where(lab_id: current_user.lab)
  end
end

app/controllers/lab_controller.rb
class LabController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  # after_action :setup_account, only: :create

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
    # super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # def sign_up(*args)
  #   super(*args)
  #     SetupAccountService.new(current_user).call if current_user.is_normal?
  # end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :first_name, :last_name, :type, :lab_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute, :first_name, :last_name, :type, :lab_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  #   events_path if current_user.is_normal?
  #   user_path(current_user) if current_user.is_admin?
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklist_components_helper.rb
module ChecklistComponentsHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/lab_helper.rb
module LabHelper
end

app/helpers/labs_helper.rb
module LabsHelper
    def select_lab
        Lab.pluck(:name, :id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def select_user_types_options
        [
          'SuperAdmin',
          'Manager',
          'Normal'
        ]
      end
end

app/views/checklist_components/index.html.slim
h1
  - @checklistComponents.each do |cc|
    => "#{cc.name}"
    = ": #{cc.completed}"
    br

app/views/experiments/index.html.slim
h1
  - @experiments.each do |exp|
    =>link_to exp.name, checklist_components_path(:experiment_id => exp.id)
    = ": #{exp.state}"
    br

app/views/lab/_admin_dashboard.html.slim
h1 Super Admin Dash

app/views/lab/_manager_dashboard.html.slim
h1 Manager Dashboard

app/views/lab/_normal_dashboard.html.slim
/ h1 Manager Dashboard
.wrapper
  = render "/shared/left-sidebar"
  /! ==============================================================
  /! Start Page Content here
  /! ==============================================================
  .content-page
    .content
      = render "/shared/topbar"
      /! Start Content
      .container-fluid
        /! start page title
        .row
          .col-12
            .page-title-box
              .page-title-right
                ol.breadcrumb.m-0
                  li.breadcrumb-item
                    a href=("javascript: void(0);")  LabSembly
                  li.breadcrumb-item
                    a href=("javascript: void(0);")  Pages
                  li.breadcrumb-item.active Dashboard
              h4.page-title User Dashboard
        /! end page title
      /! container
    /! content
    = render "/shared/footer"
  /! ==============================================================
  /! End Page content
  /! ==============================================================
/! END wrapper
= render "/shared/right-sidebar"
/! bundle
script src="assets/js/vendor.min.js" 
script src="assets/js/app.min.js" 

app/views/lab/_super_admin_dashboard.html.slim
/ h1 Manager Dashboard
.wrapper
  = render "/shared/left-sidebar"
  /! ==============================================================
  /! Start Page Content here
  /! ==============================================================
  .content-page
    .content
      = render "/shared/topbar"
      /! Start Content
      .container-fluid
        /! start page title
        .row
          .col-12
            .page-title-box
              .page-title-right
                ol.breadcrumb.m-0
                  li.breadcrumb-item
                    a href=("javascript: void(0);")  LabSembly
                  li.breadcrumb-item
                    a href=("javascript: void(0);")  Pages
                  li.breadcrumb-item.active Dashboard
              h4.page-title Super Admin Dashboard
        /! end page title
      /! container
    /! content
    = render "/shared/footer"
  /! ==============================================================
  /! End Page content
  /! ==============================================================
/! END wrapper
= render "/shared/right-sidebar"
/! bundle
script src="assets/js/vendor.min.js" 
script src="assets/js/app.min.js" 

app/views/lab/_user_dashboard.html.slim
h1 User Dashboard

app/views/lab/index.html.slim
-if current_user.is_normal?
  = render "user_dashboard"

-if current_user.is_manager?
  = render "manager_dashboard"

-if current_user.is_super_admin?
  = render "admin_dashboard"

= button_to 'Edit User', edit_user_registration_path(current_user), method: :get
= button_to 'Log out', destroy_user_session_path, method: :delete
= button_to 'Experiments', experiments_path, method: :get

app/views/lab/show.html.slim
h1 Lab#show
p Find me in app/views/lab/show.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>Hyper - Responsive Bootstrap 4 Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'icons', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <div class="wrapper">
    <%= render 'partials/left-sidebar.html'%>
    <div class="content-page">
      <div class="content">
        <%= render 'partials/topbar.html'%>
        <%= yield %>
      </div>
      <%= render 'partials/footer.html'%>
    </div>
  </div>

  <%= render 'partials/right-sidebar.html'%>

  <%= javascript_include_tag 'vendor', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>

</html>

app/views/layouts/application.html.slim
/ doctype html
/ html
/   head
/     title LabSembly | Laboratory Management Tool
/     link href="#{image_url('favicon.ico')}" rel=("shortcut icon")
/     meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
/     meta content="width=device-width, initial-scale=1.0" name="viewport"
/     meta content="Laboratory Management Tool"
/     meta content="LabSembly" name="LabSembly"
/     meta content="IE=edge" http-equiv="X-UA-Compatible"
/     = csrf_meta_tags
/     = csp_meta_tag
/     / = stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
/     / = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
/     = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
/     = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
/     / = javascript_pack_tag 'application'
/     / = stylesheet_pack_tag 'application'
/   body
/     = yield

doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    title Hyper - Responsive Bootstrap 4 Admin Dashboard
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    meta content="Coderthemes" name="author" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    link href="#{image_url('favicon.ico')}" rel=("shortcut icon") /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'icons', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = javascript_include_tag 'vendor', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>Hyper - Responsive Bootstrap 4 Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
  <meta content="Coderthemes" name="author" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <link rel="shortcut icon" href="<%= image_url('favicon.ico') %>" />

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'icons', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'app', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <div class="wrapper">
    <%= render 'layouts/partials/left-sidebar'%>
    <div class="content-page">
      <div class="content">
        <%= render 'layouts/partials/topbar'%>
        <%= yield %>
      </div>
      <%= render 'layouts/partials/footer'%>
    </div>
  </div>

  <%= render 'layouts/partials/right-sidebar'%>


  <%= javascript_include_tag 'vendor', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>

</html>

app/views/partials/_footer.html.erb
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                LabSembly
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-md-block">
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->

app/views/partials/_right-sidebar.html.erb
<!-- Right Sidebar -->
<div class="right-bar">

  <div class="rightbar-title">
    <a href="javascript:void(0);" class="right-bar-toggle float-right">
      <i class="dripicons-cross noti-icon"></i>
    </a>
    <h5 class="m-0">Settings</h5>
  </div>

  <div class="rightbar-content h-100" data-simplebar>

    <div class="p-3">
      <div class="alert alert-warning" role="alert">
        <strong>Customize </strong> the overall color scheme, sidebar menu, etc. Note that, Hyper stores the preferences
        in local storage.
      </div>

      <!-- Settings -->
      <h5 class="mt-3">Color Scheme</h5>
      <hr class="mt-1" />

      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="color-scheme-mode" value="light" id="light-mode-check"
          checked />
        <label class="custom-control-label" for="light-mode-check">Light Mode</label>
      </div>

      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="color-scheme-mode" value="dark" id="dark-mode-check" />
        <label class="custom-control-label" for="dark-mode-check">Dark Mode</label>
      </div>

      <!-- Width -->
      <h5 class="mt-4">Width</h5>
      <hr class="mt-1"/>
      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="width" value="fluid" id="fluid-check" checked />
        <label class="custom-control-label" for="fluid-check">Fluid</label>
      </div>
      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="width" value="boxed" id="boxed-check" />
        <label class="custom-control-label" for="boxed-check">Boxed</label>
      </div>

      <!-- Left Sidebar-->
      <h5 class="mt-4">Left Sidebar</h5>
      <hr class="mt-1" />
      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="theme" value="default" id="default-check" checked />
        <label class="custom-control-label" for="default-check">Default</label>
      </div>

      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="theme" value="light" id="light-check" />
        <label class="custom-control-label" for="light-check">Light</label>
      </div>

      <div class="custom-control custom-switch mb-3">
        <input type="radio" class="custom-control-input" name="theme" value="dark" id="dark-check" />
        <label class="custom-control-label" for="dark-check">Dark</label>
      </div>

      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="compact" value="fixed" id="fixed-check" checked />
        <label class="custom-control-label" for="fixed-check">Fixed</label>
      </div>

      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="compact" value="condensed" id="condensed-check" />
        <label class="custom-control-label" for="condensed-check">Condensed</label>
      </div>

      <div class="custom-control custom-switch mb-1">
        <input type="radio" class="custom-control-input" name="compact" value="scrollable" id="scrollable-check" />
        <label class="custom-control-label" for="scrollable-check">Scrollable</label>
      </div>

      <button class="btn btn-primary btn-block mt-4" id="resetBtn">Reset to Default</button>

      <a href="https://themes.getbootstrap.com/product/hyper-responsive-admin-dashboard-template/" class="btn btn-danger btn-block mt-3" target="_blank"><i class="mdi mdi-basket mr-1"></i> Purchase Now</a>
    </div> <!-- end padding-->

  </div>
</div>

<div class="rightbar-overlay"></div>
<!-- /Right-bar -->

app/views/partials/_topbar-dark.html.erb
<!-- Topbar Start -->
<div class="navbar-custom topnav-navbar topnav-navbar-dark">
    <div class="container-fluid">

        <!-- LOGO -->
        <a href="index.html" class="topnav-logo">
            <span class="topnav-logo-lg">
                <img src="assets/images/logo-light.png" alt="" height="16">
            </span>
            <span class="topnav-logo-sm">
                <img src="assets/images/logo_sm.png" alt="" height="16">
            </span>
        </a>

        <ul class="list-unstyled topbar-right-menu float-right mb-0">

            <li class="dropdown notification-list">
                <a class="nav-link right-bar-toggle" href="javascript: void(0);">
                    <i class="dripicons-gear noti-icon"></i>
                </a>
            </li>
            <li class="dropdown notification-list topbar-dropdown d-none d-lg-block">
                <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" id="topbar-languagedrop" href="#"
                    role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="assets/images/flags/us.jpg" alt="user-image" class="mr-1" height="12"> <span
                        class="align-middle">English</span> <i class="mdi mdi-chevron-down"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated topbar-dropdown-menu"
                    aria-labelledby="topbar-languagedrop">

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="assets/images/flags/germany.jpg" alt="user-image" class="mr-1" height="12"> <span
                            class="align-middle">German</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="assets/images/flags/italy.jpg" alt="user-image" class="mr-1" height="12"> <span
                            class="align-middle">Italian</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="assets/images/flags/spain.jpg" alt="user-image" class="mr-1" height="12"> <span
                            class="align-middle">Spanish</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <img src="assets/images/flags/russia.jpg" alt="user-image" class="mr-1" height="12"> <span
                            class="align-middle">Russian</span>
                    </a>

                </div>
            </li>

            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" id="topbar-notifydrop"
                    role="button" aria-haspopup="true" aria-expanded="false">
                    <i class="dripicons-bell noti-icon"></i>
                    <span class="noti-icon-badge"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg"
                    aria-labelledby="topbar-notifydrop">

                    <!-- item-->
                    <div class="dropdown-item noti-title">
                        <h5 class="m-0">
                            <span class="float-right">
                                <a href="javascript: void(0);" class="text-dark">
                                    <small>Clear All</small>
                                </a>
                            </span>Notification
                        </h5>
                    </div>

                    <div style="max-height: 230px;" data-simplebar>
                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-primary">
                                <i class="mdi mdi-comment-account-outline"></i>
                            </div>
                            <p class="notify-details">Caleb Flakelar commented on Admin
                                <small class="text-muted">1 min ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info">
                                <i class="mdi mdi-account-plus"></i>
                            </div>
                            <p class="notify-details">New user registered.
                                <small class="text-muted">5 hours ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon">
                                <img src="assets/images/users/avatar-2.jpg" class="img-fluid rounded-circle" alt="" />
                            </div>
                            <p class="notify-details">Cristina Pride</p>
                            <p class="text-muted mb-0 user-msg">
                                <small>Hi, How are you? What about our next meeting</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-primary">
                                <i class="mdi mdi-comment-account-outline"></i>
                            </div>
                            <p class="notify-details">Caleb Flakelar commented on Admin
                                <small class="text-muted">4 days ago</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon">
                                <img src="assets/images/users/avatar-4.jpg" class="img-fluid rounded-circle" alt="" />
                            </div>
                            <p class="notify-details">Karen Robinson</p>
                            <p class="text-muted mb-0 user-msg">
                                <small>Wow ! this admin looks good and awesome design</small>
                            </p>
                        </a>

                        <!-- item-->
                        <a href="javascript:void(0);" class="dropdown-item notify-item">
                            <div class="notify-icon bg-info">
                                <i class="mdi mdi-heart"></i>
                            </div>
                            <p class="notify-details">Carlos Crouch liked
                                <b>Admin</b>
                                <small class="text-muted">13 days ago</small>
                            </p>
                        </a>
                    </div>

                    <!-- All-->
                    <a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
                        View All
                    </a>

                </div>
            </li>
            
            <li class="dropdown notification-list">
                <a class="nav-link dropdown-toggle nav-user arrow-none mr-0" data-toggle="dropdown" id="topbar-userdrop"
                    href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <span class="account-user-avatar">
                        <img src="assets/images/users/avatar-1.jpg" alt="user-image" class="rounded-circle">
                    </span>
                    <span>
                        <span class="account-user-name">Dominic Keller</span>
                        <span class="account-position">Founder</span>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated topbar-dropdown-menu profile-dropdown"
                    aria-labelledby="topbar-userdrop">
                    <!-- item-->
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome !</h6>
                    </div>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-account-circle mr-1"></i>
                        <span>My Account</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-account-edit mr-1"></i>
                        <span>Settings</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-lifebuoy mr-1"></i>
                        <span>Support</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-lock-outline mr-1"></i>
                        <span>Lock Screen</span>
                    </a>

                    <!-- item-->
                    <a href="javascript:void(0);" class="dropdown-item notify-item">
                        <i class="mdi mdi-logout mr-1"></i>
                        <span>Logout</span>
                    </a>

                </div>
            </li>

        </ul>
        <a class="button-menu-mobile disable-btn">
            <div class="lines">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </a>
        <div class="app-search">
            <form>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="mdi mdi-magnify"></span>
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- end Topbar -->

app/views/shared/_footer.html.erb
<!-- Footer Start -->
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                2018 - 2020 © Hyper - Coderthemes.com
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-md-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end Footer -->